name: build phonefarm apk
on:
  workflow_dispatch: # 手动选择分支

permissions:
  actions: write
  attestations: write
  checks: write
  contents: write
  deployments: write
  discussions: write
  issues: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 设置变量
      - name: Set output
        id: vars
        run: |
          echo "short_ref=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: 下载源码
        id: check
        uses: actions/checkout@v4

      - name: 初始化 JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: 初始化 Android SDK
        uses: android-actions/setup-android@v3

      - name: 初始化 Gradle
        uses: gradle/gradle-build-action@v3

      - name: 打包模版 APP
        run: |
          chmod 777 ./gradlew
          ./gradlew phonefarm:buildTemplateApp

      - name: 打包 PhoneFarm App
        run: |
          ./gradlew phonefarm:assembleV6

      - name: 对 APP 进行签名
        uses: Tlaster/android-sign@v1.2.2
        with:
          releaseDirectory: |
            phonefarm/build/outputs/apk/v6/release
          signingKeyBase64: ${{ secrets.ASIGNING_KEY }}
          alias: ${{ secrets.AALIAS }}
          keyStorePassword: ${{ secrets.AKEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.AKEY_PASSWORD }}
          output: build/phonefarm/signed
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: 重命名 apk
        run: |
          cd build/phonefarm/signed
          mv phonefarm-v6-arm64-v8a-*.apk PhoneFarm-v6-arm64-v8a-release-${{steps.vars.outputs.short_ref}}.apk
          mv phonefarm-v6-armeabi-v7a-*.apk PhoneFarm-v6-armeabi-v7a-release-${{steps.vars.outputs.short_ref}}.apk
          mv phonefarm-v6-universal-*.apk PhoneFarm-v6-universal-release-${{steps.vars.outputs.short_ref}}.apk
          ls

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: |
            [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/${{steps.vars.outputs.short_ref}}/CHANGELOG.md)
          # 匹配目录下所有文件
          files: 'build/phonefarm/signed/**'
          draft: true  # 草稿
